# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-11 06:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2017, 7, 11, 6, 34, 46, 33353, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='date_published',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date published'),
        ),
    ]
